#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          15

bspc config top_padding 40
bspc config right_padding 5
bspc config bottom_padding 10
bspc config left_padding 5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true
bscp config pointer_follows_monitor true

# bspc config focused_border_color '#FFFFFF'
# bspc config normal_border_color '#232627'
# bspc config presel_feedback_color '6b6b69'
bspc config border_width 0

bspc rule -a Spotify desktop=^10
bspc rule -a cmus desktop=^10
bspc rule -a Gcolor3 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

 
pkill sxhkd
pkill picom
pkill xss-lock
pkill polybar
pkill flashfocus

nitrogen --restore &

xsetroot -cursor_name left_ptr

sxhkd &
picom &

xfce4-power-manager
xss-lock --transfer-sleep-lock -- ~/bin/i3lock-command.sh &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

dunst &
flashfocus &

xset b off
setxkbmap -model pc101 -layout us -option caps:escape_shifted_capslock

polybar BSPNU &

