#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#376076'

hc pad 0 54 12 10 12
# remove all existing keybindings
hc keyunbind --all

TERMINAL=kitty

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
Mod=Mod1    # Use alt as the main modifier
#Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-q close
hc keybind $Mod-Shift-r reload
#hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn ${TERMINAL:-xterm} # use your $TERMINAL with xterm as fallback

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-j     focus left
hc keybind $Mod-k     focus down
hc keybind $Mod-l     focus up
hc keybind $Mod-semicolon     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-j     shift left
hc keybind $Mod-Shift-k     shift down
hc keybind $Mod-Shift-l     shift up
hc keybind $Mod-Shift-semicolon     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.01
hc keybind $Mod-Control-j       resize left +$resizestep
hc keybind $Mod-Control-k       resize down +$resizestep
hc keybind $Mod-Control-l       resize up +$resizestep
hc keybind $Mod-Control-semicolon       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..4} )
tag_keys=( {1..4} )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

hc add ''
hc keybind $Mod-'0' use_index 4
hc keybind $Mod-Shift-'0' move_index 4

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-q close_or_remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-Shift-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-a                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind Mod4-Tab   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent
hc keybind $Mod-n spawn nc_flash_window

## Volume Control
# Use pulseaudio-control script for better control over volume
hc keybind XF86AudioRaiseVolume spawn pactl set-sink-volume @DEFAULT_SINK@ +5%
hc keybind XF86AudioLowerVolume spawn pactl set-sink-volume @DEFAULT_SINK@ -5%
#hc keybind XF86AudioMute spawn ~/.config/polybar/scripts/pulseaudio-control.sh --togmute
hc keybind XF86AudioMicMute spawn pactl set-source-mute @DEFAULT_SOURCE@ toggle

# Media Control
hc keybind $Mod-slash spawn playerctl play-pause
hc keybind $Mod-period spawn playerctl next
hc keybind $Mod-comma spawn playerctl previous

# Other keybindings
hc keybind $Mod-space spawn rofi -show drun -show-icons
hc keybind $Mod-Shift-n spawn networkmanager_dmenu
hc keybind $Mod-Shift-e spawn ~/bin/powermenu.sh
hc keybind Mod4-p spawn ~/bin/display_modes.sh

# Lock Screen
hc keybind Mod4-l spawn loginctl lock-session

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#75cfcf'
hc set frame_border_width 0
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 2
hc set frame_gap 10
hc set frame_padding 0

hc attr theme.active.color '#9fbc00'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color orange
hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.border_width 0
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'

hc set window_gap 5
hc set frame_padding 0
hc set smart_window_surroundings 1
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

# rules
hc unrule -F
hc rule focus=on # normally focus new clients
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule class='Spotify' tag=

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

hc spawn pkill picom
hc spawn pkill dunst
hc spawn pkill xss-lock
hc spawn pkill polybar
hc spawn pkill flashfocus

hc spawn xset b off
hc spawn xinput set-prop "ELAN1301:00 04F3:3128 Touchpad" "libinput Tapping Enabled" 1
hc spawn xinput set-prop "ELAN1301:00 04F3:3128 Touchpad" "libinput Natural Scrolling Enabled" 1
hc spawn xinput set-prop "ELAN1301:00 04F3:3128 Touchpad" "libinput Middle Emulation Enabled" 1
hc spawn setxkbmap -model pc101 -layout us -option caps:escape_shifted_capslock
hc spawn nitrogen --restore &

hc spawn xss-lock --transfer-sleep-lock -- ~/bin/i3lock-command.sh &

hc spawn xfce4-power-manager

hc spawn /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &


hc spawn picom &
hc spawn flashfocus &
hc spawn dunst &
hc spawn polybar HLNU
